EXPAND_CONFIG

diff --git a/.github/workflows/validate-config.yaml b/.github/workflows/validate-config.yaml
--- a/.github/workflows/validate-config.yaml
+++ b/.github/workflows/validate-config.yaml
@@ -37,8 +37,11 @@ jobs:
         echo "$TEST_PROJECT_SA_KEY" > rendered/broad/tanagra_sa.json
       env:
         TEST_PROJECT_SA_KEY: ${{ secrets.TEST_PROJECT_SA_KEY }}
-    - name: Gradle Build and Check
-      # The check task includes the build, test and static analysis tasks.
-      run: ./gradlew underlay:check
+    - name: Expand config
+      run: |
+        ./gradlew indexer:index -Dexec.args="EXPAND_CONFIG /Users/melchang/tanagra/service/src/main/resources/config/verily/aou_synthetic/original/aou_synthetic.json /Users/melchang/tanagra/service/src/main/resources/config/verily/aou_synthetic/expanded"
+        git status
+        # This will fail if there are new files in the working directory 
+        exit $(git status -s -uno | wc -l)
       env:
         GOOGLE_APPLICATION_CREDENTIALS: ../rendered/broad/tanagra_sa.json
